import type { CampusItem, CampusNotification, StudentProfile } from "./campusfind-types";

export const CAMPUS_PROFILE: StudentProfile = {
  name: "Alex Morgan",
  department: "Computer Science",
  year: "Year 3 · Class of 2027",
  initials: "AM",
};

export const SEED_ITEMS: CampusItem[] = [
  {
    id: "found-earbuds-1",
    name: "Black Wireless Earbuds",
    category: "Electronics",
    description: "A compact black charging case with wireless earbuds inside.",
    status: "found",
    location: "Central Library",
    date: "2026-10-04",
    time: "2:20 PM",
    color: "Black",
    reporter: "Jordan Lee",
    initials: "JL",
    photo: "/manus-storage/black-samsung-buds_3fc8e97d.jpg",
    postedAt: "2026-10-04T14:30:00.000Z",
  },
  {
    id: "found-earbuds-2",
    name: "Black Samsung Earbuds",
    category: "Electronics",
    description: "Small black earbuds found beside the student café seating.",
    status: "found",
    location: "Cafeteria",
    date: "2026-10-04",
    time: "12:10 PM",
    color: "Black",
    reporter: "Priya Shah",
    initials: "PS",
    postedAt: "2026-10-04T12:20:00.000Z",
  },
  {
    id: "found-earbuds-3",
    name: "Wireless Earbud Case",
    category: "Electronics",
    description: "Black case with one earbud still inside, found near the reading wing.",
    status: "found",
    location: "Library Annex",
    date: "2026-10-03",
    time: "4:45 PM",
    color: "Black",
    reporter: "Noah Williams",
    initials: "NW",
    postedAt: "2026-10-03T16:50:00.000Z",
  },
  {
    id: "lost-wallet-1",
    name: "Black Leather Wallet",
    category: "ID/Cards",
    description: "Slim black wallet with a student ID and a few cards.",
    status: "lost",
    location: "Library",
    date: "2026-10-05",
    time: "11:30 AM",
    color: "Black",
    reporter: "Alex Morgan",
    initials: "AM",
    photo: "/manus-storage/black-leather-wallet_8202c81c.jpg",
    postedAt: "2026-10-05T11:40:00.000Z",
  },
  {
    id: "found-wallet-1",
    name: "Black Wallet",
    category: "ID/Cards",
    description: "Found a black wallet near the library entrance. Kept safe at the desk.",
    status: "found",
    location: "Library",
    date: "2026-10-05",
    time: "12:05 PM",
    color: "Black",
    reporter: "Sam Rivera",
    initials: "SR",
    photo: "/manus-storage/black-leather-wallet_8202c81c.jpg",
    postedAt: "2026-10-05T12:10:00.000Z",
  },
  {
    id: "lost-bottle-1",
    name: "Sage Green Water Bottle",
    category: "Personal Items",
    description: "Reusable bottle with a small constellation sticker on the side.",
    status: "lost",
    location: "Sports Ground",
    date: "2026-10-05",
    time: "5:15 PM",
    color: "Sage green",
    reporter: "Maya Chen",
    initials: "MC",
    postedAt: "2026-10-05T17:30:00.000Z",
  },
  {
    id: "found-bottle-1",
    name: "Green Hydro Flask",
    category: "Personal Items",
    description: "Green insulated water bottle, left beside the bleachers.",
    status: "found",
    location: "Sports Ground",
    date: "2026-10-05",
    time: "5:40 PM",
    color: "Green",
    reporter: "Ethan Brooks",
    initials: "EB",
    postedAt: "2026-10-05T17:45:00.000Z",
  },
  {
    id: "lost-tote-1",
    name: "Canvas Book Tote",
    category: "Bags",
    description: "Natural canvas tote with a blue flower printed on the front.",
    status: "lost",
    location: "Main Block",
    date: "2026-10-06",
    time: "9:00 AM",
    color: "Natural / blue",
    reporter: "Taylor Kim",
    initials: "TK",
    photo: "/manus-storage/campus-backpack_bf5f4c66.jpg",
    postedAt: "2026-10-06T09:15:00.000Z",
  },
  {
    id: "found-tote-1",
    name: "Beige Canvas Tote Bag",
    category: "Bags",
    description: "Light canvas tote with notebooks inside, picked up near the stairs.",
    status: "found",
    location: "Main Block",
    date: "2026-10-06",
    time: "9:35 AM",
    color: "Beige",
    reporter: "Ava Patel",
    initials: "AP",
    postedAt: "2026-10-06T09:45:00.000Z",
  },
  {
    id: "lost-notebook-1",
    name: "Blue Economics Notebook",
    category: "Books",
    description: "A5 ruled notebook with ECON 204 written on the inside cover.",
    status: "lost",
    location: "Computer Lab",
    date: "2026-10-05",
    time: "3:30 PM",
    color: "Blue",
    reporter: "Jamie Park",
    initials: "JP",
    photo: "/manus-storage/campus-student-books_8311246a.jpg",
    postedAt: "2026-10-05T15:40:00.000Z",
  },
  {
    id: "found-keys-1",
    name: "Keys with a Tiny Moon Keychain",
    category: "Keys",
    description: "Three keys on a silver ring with a small crescent-moon charm.",
    status: "found",
    location: "Hostel",
    date: "2026-10-06",
    time: "8:10 AM",
    color: "Silver",
    reporter: "Riley Davis",
    initials: "RD",
    postedAt: "2026-10-06T08:20:00.000Z",
  },
  {
    id: "lost-card-1",
    name: "Student ID Card",
    category: "ID/Cards",
    description: "Campus ID in a clear sleeve with a blue lanyard.",
    status: "lost",
    location: "Cafeteria",
    date: "2026-10-06",
    time: "1:05 PM",
    color: "Blue / clear",
    reporter: "Casey Patel",
    initials: "CP",
    postedAt: "2026-10-06T13:15:00.000Z",
  },
  {
    id: "found-accessories-1",
    name: "Silver Star Hair Clip",
    category: "Accessories",
    description: "Small silver hair clip with a tiny star detail, found near the campus gate.",
    status: "found",
    location: "Parking Area",
    date: "2026-10-06",
    time: "2:35 PM",
    color: "Silver",
    reporter: "Nina Kapoor",
    initials: "NK",
    postedAt: "2026-10-06T14:42:00.000Z",
  },
  {
    id: "lost-clothing-1",
    name: "Navy Knit Cardigan",
    category: "Clothing",
    description: "Soft navy cardigan with wooden buttons, last seen after class.",
    status: "lost",
    location: "Main Block",
    date: "2026-10-06",
    time: "11:25 AM",
    color: "Navy",
    reporter: "Morgan Ellis",
    initials: "ME",
    postedAt: "2026-10-06T11:40:00.000Z",
  },
  {
    id: "lost-stationery-1",
    name: "Lavender Pencil Case",
    category: "Stationery",
    description: "Lavender zip pouch with a few gel pens and a tiny moon sticker.",
    status: "lost",
    location: "Computer Lab",
    date: "2026-10-05",
    time: "4:05 PM",
    color: "Lavender",
    reporter: "Jamie Park",
    initials: "JP",
    postedAt: "2026-10-05T16:10:00.000Z",
  },
  {
    id: "found-other-1",
    name: "Clear Compact Umbrella",
    category: "Other",
    description: "Foldable clear umbrella left beside a parking-area bench.",
    status: "found",
    location: "Parking Area",
    date: "2026-10-06",
    time: "1:50 PM",
    color: "Clear",
    reporter: "Devon Brooks",
    initials: "DB",
    postedAt: "2026-10-06T14:00:00.000Z",
  },
];

export const SEED_NOTIFICATIONS: CampusNotification[] = [
  {
    id: "wallet-match-notification",
    title: "New Match Found!",
    body: "Your black wallet has a 91% match with a recently found item.",
    location: "Library",
    date: "2026-10-05",
    matchScore: 91,
    read: false,
  },
  {
    id: "earbud-match-notification",
    title: "A match is looking promising",
    body: "Three found-item posts look close to your black Samsung earbuds.",
    location: "Central Library",
    date: "2026-10-04",
    matchScore: 94,
    read: false,
  },
];

export const MOST_REPORTED_LOCATIONS = [
  { name: "Library", count: 24, color: "mint" },
  { name: "Cafeteria", count: 18, color: "violet" },
  { name: "Main Block", count: 15, color: "blue" },
] as const;

export const CAMPUS_STATS = [
  { value: "127+", label: "Items Reported", icon: "package" },
  { value: "84", label: "Successful Matches", icon: "sparkles" },
  { value: "12", label: "Active Today", icon: "activity" },
  { value: "95%", label: "Match Accuracy", icon: "target" },
] as const;

export const IMPACT_STATS = [
  { value: "84", label: "Items reunited" },
  { value: "72", label: "Students helped" },
  { value: "95%", label: "Successful matches" },
  { value: "1.2k", label: "Active users" },
] as const;
